import 'package:tv_series/data/models/tv_series_table.dart';
import 'package:tv_series/domain/entities/episode.dart';
import 'package:tv_series/domain/entities/genre.dart';
import 'package:tv_series/domain/entities/season.dart';
import 'package:tv_series/domain/entities/tv_series.dart';
import 'package:tv_series/domain/entities/tv_series_detail.dart';

final testTvSeries = TvSeries(
  backdropPath: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
  firstAirDate: "2011-04-17",
  genreIds: const [10765, 18, 10759],
  id: 1399,
  name: "Game of Thrones",
  originCountry: const ["US"],
  originalLanguage: "en",
  originalName: "Game of Thrones",
  overview: "Seven noble families fig…and icy horrors beyond.",
  popularity: 590.57,
  posterPath: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
  voteAverage: 8.43,
  voteCount: 19849,
);

final testTvSeriesList = [testTvSeries];

const testTvSeriesDetail = TvSeriesDetail(
  adult: false,
  backdropPath: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
  firstAirDate: "2011-04-17",
  genres: [
    Genre(id: 10765, name: "Sci-Fi & Fantasy"),
    Genre(id: 18, name: "Drama"),
    Genre(id: 10759, name: "Action & Adventure"),
  ],
  homepage: "http://www.hbo.com/game-of-thrones",
  id: 1399,
  inProduction: false,
  languages: ["en"],
  lastAirDate: "2019-05-19",
  lastEpisodeToAir: Episode(
    airDate: "2019-05-19",
    episodeNumber: 6,
    id: 1551830,
    name: "The Iron Throne",
    overview: "In the aftermath of the …ust face the survivors.",
    productionCode: "806",
    runtime: 80,
    seasonNumber: 8,
    showId: 1399,
    stillPath: "/zBi2O5EJfgTS6Ae0HdAYLm9o2nf.jpg",
    voteAverage: 4.7,
    voteCount: 209,
  ),
  name: "Game of Thrones",
  nextEpisodeToAir: null,
  numberOfEpisodes: 73,
  numberOfSeasons: 8,
  originCountry: ["US"],
  originalLanguage: "en",
  originalName: "Game of Thrones",
  overview: "Seven noble families fig…and icy horrors beyond.",
  popularity: 590.57,
  posterPath: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
  seasons: [
    Season(
      sId: null,
      airDate: "2010-12-05",
      episodes: null,
      episodeCount: 260,
      name: "Specials",
      overview: "",
      id: 3267,
      posterPath: "/kMTcwNRfFKCZ0O2OaBZS0nZ2AIe.jpg",
      seasonNumber: 0,
    ),
    Season(
      sId: null,
      airDate: "2011-04-17",
      episodes: null,
      episodeCount: 10,
      name: "Season 1",
      overview: "Trouble is brewing in th…ten danger is stirring.",
      id: 3264,
      posterPath: "/wgfKiqzuMrFIkU1M68DDDY8kGC1.jpg",
      seasonNumber: 1,
    ),
  ],
  status: "Ended",
  tagline: "Winter Is Coming",
  type: "Scripted",
  voteAverage: 8.43,
  voteCount: 19849,
);

const testTvSeriesDetailWithNextEpisode = TvSeriesDetail(
  adult: false,
  backdropPath: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
  firstAirDate: "2011-04-17",
  genres: [
    Genre(id: 10765, name: "Sci-Fi & Fantasy"),
    Genre(id: 18, name: "Drama"),
    Genre(id: 10759, name: "Action & Adventure"),
  ],
  homepage: "http://www.hbo.com/game-of-thrones",
  id: 1399,
  inProduction: false,
  languages: ["en"],
  lastAirDate: "2019-05-19",
  lastEpisodeToAir: Episode(
    airDate: "2019-05-19",
    episodeNumber: 6,
    id: 1551830,
    name: "The Iron Throne",
    overview: "In the aftermath of the …ust face the survivors.",
    productionCode: "806",
    runtime: 80,
    seasonNumber: 8,
    showId: 1399,
    stillPath: "/zBi2O5EJfgTS6Ae0HdAYLm9o2nf.jpg",
    voteAverage: 4.7,
    voteCount: 209,
  ),
  name: "Game of Thrones",
  nextEpisodeToAir: Episode(
    airDate: "2019-05-19",
    episodeNumber: 6,
    id: 1551830,
    name: "The Iron Throne",
    overview: "In the aftermath of the …ust face the survivors.",
    productionCode: "806",
    runtime: 80,
    seasonNumber: 8,
    showId: 1399,
    stillPath: "/zBi2O5EJfgTS6Ae0HdAYLm9o2nf.jpg",
    voteAverage: 4.7,
    voteCount: 209,
  ),
  numberOfEpisodes: 73,
  numberOfSeasons: 8,
  originCountry: ["US"],
  originalLanguage: "en",
  originalName: "Game of Thrones",
  overview: "Seven noble families fig…and icy horrors beyond.",
  popularity: 590.57,
  posterPath: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
  seasons: [
    Season(
      sId: null,
      airDate: "2010-12-05",
      episodes: null,
      episodeCount: 260,
      name: "Specials",
      overview: "",
      id: 3267,
      posterPath: "/kMTcwNRfFKCZ0O2OaBZS0nZ2AIe.jpg",
      seasonNumber: 0,
    ),
    Season(
      sId: null,
      airDate: "2011-04-17",
      episodes: null,
      episodeCount: 10,
      name: "Season 1",
      overview: "Trouble is brewing in th…ten danger is stirring.",
      id: 3264,
      posterPath: "/wgfKiqzuMrFIkU1M68DDDY8kGC1.jpg",
      seasonNumber: 1,
    ),
  ],
  status: "Ended",
  tagline: "Winter Is Coming",
  type: "Scripted",
  voteAverage: 8.43,
  voteCount: 19849,
);

final testWatchlistTvSeries = TvSeries.watchlist(
  id: 1399,
  overview: "Seven noble families fig…and icy horrors beyond.",
  posterPath: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
  name: "Game of Thrones",
);

const testTvSeriesTable = TvSeriesTable(
  id: 1399,
  name: "Game of Thrones",
  posterPath: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
  overview: "Seven noble families fig…and icy horrors beyond.",
);

final testTvSeriesMap = {
  'id': 1399,
  'name': 'Game of Thrones',
  'posterPath': '/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg',
  'overview': 'Seven noble families fig…and icy horrors beyond.',
};
