// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdr7ukpYexeGsOooPHPcvLhgHeh7I6pj0',
    appId: '1:874490684734:web:c92e01f833aeeca30af86f',
    messagingSenderId: '874490684734',
    projectId: 'ditonton-f1d7f',
    authDomain: 'ditonton-f1d7f.firebaseapp.com',
    storageBucket: 'ditonton-f1d7f.appspot.com',
    measurementId: 'G-1Q2PL0M7VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzYOYNevrNnierYRrN5Ey757ndKi2_U0Y',
    appId: '1:874490684734:android:6b1d41a3f81fa1a60af86f',
    messagingSenderId: '874490684734',
    projectId: 'ditonton-f1d7f',
    storageBucket: 'ditonton-f1d7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSz9TYZZmBPcr18ZkuiIZDI5utxXNsYo',
    appId: '1:874490684734:ios:7e4a00d1b413bbef0af86f',
    messagingSenderId: '874490684734',
    projectId: 'ditonton-f1d7f',
    storageBucket: 'ditonton-f1d7f.appspot.com',
    iosClientId: '874490684734-jb5koucc0ml6f6iqtaoko7jpjnjarict.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
